import { Component, inject } from '@angular/core';
import { IonApp, IonRouterOutlet } from '@ionic/angular/standalone';
import { addIcons } from 'ionicons';
import {
  mailOutline,
  lockClosedOutline,
  alertCircleOutline,
  shieldCheckmark,
  logOutOutline,
  gridOutline,
  cubeOutline,
  peopleOutline,
  imagesOutline,
  pricetagsOutline,
  colorPaletteOutline,
  settingsOutline,
  imageOutline,
  createOutline,
  trashOutline,
  addCircleOutline,
  openOutline,
  keyOutline,
  personAddOutline,
  searchOutline,
  cartOutline,
  lockOpenOutline,
  personOutline,
  logoWhatsapp,
  logoInstagram,
  logoFacebook,
  locationOutline,
  timeOutline,
  callOutline,
  copyOutline,
  checkmarkCircleOutline,
  closeCircleOutline,
  eyeOutline,
  eyeOffOutline,
  arrowBackOutline,
  star,
  starOutline,
  funnelOutline,
  swapVerticalOutline,
  closeOutline,
  homeOutline,
  flameOutline,
  sparklesOutline,
  refreshOutline,
  saveOutline,
  informationCircleOutline,
  checkmarkOutline,
  arrowForwardOutline
} from 'ionicons/icons';
import { ServicioTema } from './services/theme/servicio-tema.service';

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  standalone: true,
  imports: [IonApp, IonRouterOutlet],
})
export class AppComponent {
  private servicioTema = inject(ServicioTema);

  constructor() {
    // Registrar iconos globales para Ionic 8 Standalone
    addIcons({
      mailOutline,
      lockClosedOutline,
      alertCircleOutline,
      shieldCheckmark,
      logOutOutline,
      gridOutline,
      cubeOutline,
      peopleOutline,
      imagesOutline,
      pricetagsOutline,
      colorPaletteOutline,
      settingsOutline,
      imageOutline,
      createOutline,
      trashOutline,
      addCircleOutline,
      openOutline,
      keyOutline,
      personAddOutline,
      searchOutline,
      cartOutline,
      lockOpenOutline,
      personOutline,
      logoWhatsapp,
      logoInstagram,
      logoFacebook,
      locationOutline,
      timeOutline,
      callOutline,
      copyOutline,
      checkmarkCircleOutline,
      closeCircleOutline,
      eyeOutline,
      eyeOffOutline,
      arrowBackOutline,
      star,
      starOutline,
      funnelOutline,
      swapVerticalOutline,
      closeOutline,
      homeOutline,
      flameOutline,
      sparklesOutline,
      refreshOutline,
      saveOutline,
      informationCircleOutline,
      checkmarkOutline,
      arrowForwardOutline,
      'mail-outline': mailOutline,
      'lock-closed-outline': lockClosedOutline,
      'alert-circle-outline': alertCircleOutline,
      'shield-checkmark': shieldCheckmark,
      'log-out-outline': logOutOutline,
      'grid-outline': gridOutline,
      'cube-outline': cubeOutline,
      'people-outline': peopleOutline,
      'images-outline': imagesOutline,
      'pricetags-outline': pricetagsOutline,
      'color-palette-outline': colorPaletteOutline,
      'settings-outline': settingsOutline,
      'image-outline': imageOutline,
      'create-outline': createOutline,
      'trash-outline': trashOutline,
      'add-circle-outline': addCircleOutline,
      'open-outline': openOutline,
      'key-outline': keyOutline,
      'person-add-outline': personAddOutline,
      'search-outline': searchOutline,
      'cart-outline': cartOutline,
      'lock-open-outline': lockOpenOutline,
      'person-outline': personOutline,
      'logo-whatsapp': logoWhatsapp,
      'logo-instagram': logoInstagram,
      'logo-facebook': logoFacebook,
      'location-outline': locationOutline,
      'time-outline': timeOutline,
      'call-outline': callOutline,
      'copy-outline': copyOutline,
      'checkmark-circle-outline': checkmarkCircleOutline,
      'close-circle-outline': closeCircleOutline,
      'eye-outline': eyeOutline,
      'eye-off-outline': eyeOffOutline,
      'arrow-back-outline': arrowBackOutline,
      'funnel-outline': funnelOutline,
      'swap-vertical-outline': swapVerticalOutline,
      'close-outline': closeOutline,
      'home-outline': homeOutline,
      'flame-outline': flameOutline,
      'sparkles-outline': sparklesOutline,
      'refresh-outline': refreshOutline,
      'save-outline': saveOutline,
      'information-circle-outline': informationCircleOutline,
      'checkmark-outline': checkmarkOutline,
      'arrow-forward-outline': arrowForwardOutline
    });
  }
}


