import { bootstrapApplication } from '@angular/platform-browser';
import { RouteReuseStrategy, provideRouter, withPreloading, PreloadAllModules } from '@angular/router';
import { IonicRouteStrategy, provideIonicAngular } from '@ionic/angular/standalone';
import { addIcons } from 'ionicons';
import {
  mailOutline,
  lockClosedOutline,
  lockClosed,
  lockOpen,
  globeOutline,
  ribbonOutline,
  shieldCheckmarkOutline,
  paperPlaneOutline,
  alertCircleOutline,
  shieldCheckmark,
  logOutOutline,
  gridOutline,
  cubeOutline,
  peopleOutline,
  imagesOutline,
  pricetagsOutline,
  colorPaletteOutline,
  settingsOutline,
  imageOutline,
  createOutline,
  trashOutline,
  addCircle,
  addCircleOutline,
  openOutline,
  keyOutline,
  personAddOutline,
  searchOutline,
  cartOutline,
  lockOpenOutline,
  personOutline,
  logoWhatsapp,
  logoInstagram,
  logoFacebook,
  locationOutline,
  timeOutline,
  callOutline,
  copyOutline,
  checkmarkCircle,
  checkmarkCircleOutline,
  closeCircle,
  closeCircleOutline,
  eyeOutline,
  eyeOffOutline,
  arrowBackOutline,
  star,
  starOutline,
  funnelOutline,
  swapVerticalOutline,
  closeOutline,
  homeOutline,
  flame,
  flameOutline,
  sparklesOutline,
  refreshOutline,
  saveOutline,
  informationCircleOutline,
  checkmarkOutline,
  arrowForwardOutline,
  powerOutline
} from 'ionicons/icons';

import { routes } from './app/app.routes';
import { AppComponent } from './app/app.component';

// Registrar todos los íconos de forma estática con claves tipo string puras (inmunes a minificación de producción)
addIcons({
  'mail-outline': mailOutline,
  'mailOutline': mailOutline,
  'lock-closed-outline': lockClosedOutline,
  'lockClosedOutline': lockClosedOutline,
  'lock-closed': lockClosed,
  'lockClosed': lockClosed,
  'lock-open': lockOpen,
  'lockOpen': lockOpen,
  'globe-outline': globeOutline,
  'globeOutline': globeOutline,
  'ribbon-outline': ribbonOutline,
  'ribbonOutline': ribbonOutline,
  'shield-checkmark-outline': shieldCheckmarkOutline,
  'shieldCheckmarkOutline': shieldCheckmarkOutline,
  'paper-plane-outline': paperPlaneOutline,
  'paperPlaneOutline': paperPlaneOutline,
  'alert-circle-outline': alertCircleOutline,
  'alertCircleOutline': alertCircleOutline,
  'shield-checkmark': shieldCheckmark,
  'shieldCheckmark': shieldCheckmark,
  'log-out-outline': logOutOutline,
  'logOutOutline': logOutOutline,
  'grid-outline': gridOutline,
  'gridOutline': gridOutline,
  'cube-outline': cubeOutline,
  'cubeOutline': cubeOutline,
  'people-outline': peopleOutline,
  'peopleOutline': peopleOutline,
  'images-outline': imagesOutline,
  'imagesOutline': imagesOutline,
  'pricetags-outline': pricetagsOutline,
  'pricetagsOutline': pricetagsOutline,
  'color-palette-outline': colorPaletteOutline,
  'colorPaletteOutline': colorPaletteOutline,
  'settings-outline': settingsOutline,
  'settingsOutline': settingsOutline,
  'image-outline': imageOutline,
  'imageOutline': imageOutline,
  'create-outline': createOutline,
  'createOutline': createOutline,
  'trash-outline': trashOutline,
  'trashOutline': trashOutline,
  'add-circle': addCircle,
  'addCircle': addCircle,
  'add-circle-outline': addCircleOutline,
  'addCircleOutline': addCircleOutline,
  'open-outline': openOutline,
  'openOutline': openOutline,
  'key-outline': keyOutline,
  'keyOutline': keyOutline,
  'person-add-outline': personAddOutline,
  'personAddOutline': personAddOutline,
  'search-outline': searchOutline,
  'searchOutline': searchOutline,
  'cart-outline': cartOutline,
  'cartOutline': cartOutline,
  'lock-open-outline': lockOpenOutline,
  'lockOpenOutline': lockOpenOutline,
  'person-outline': personOutline,
  'personOutline': personOutline,
  'logo-whatsapp': logoWhatsapp,
  'logoWhatsapp': logoWhatsapp,
  'logo-instagram': logoInstagram,
  'logoInstagram': logoInstagram,
  'logo-facebook': logoFacebook,
  'logoFacebook': logoFacebook,
  'location-outline': locationOutline,
  'locationOutline': locationOutline,
  'time-outline': timeOutline,
  'timeOutline': timeOutline,
  'call-outline': callOutline,
  'callOutline': callOutline,
  'copy-outline': copyOutline,
  'copyOutline': copyOutline,
  'checkmark-circle': checkmarkCircle,
  'checkmarkCircle': checkmarkCircle,
  'checkmark-circle-outline': checkmarkCircleOutline,
  'checkmarkCircleOutline': checkmarkCircleOutline,
  'close-circle': closeCircle,
  'closeCircle': closeCircle,
  'close-circle-outline': closeCircleOutline,
  'closeCircleOutline': closeCircleOutline,
  'eye-outline': eyeOutline,
  'eyeOutline': eyeOutline,
  'eye-off-outline': eyeOffOutline,
  'eyeOffOutline': eyeOffOutline,
  'arrow-back-outline': arrowBackOutline,
  'arrowBackOutline': arrowBackOutline,
  'star': star,
  'star-outline': starOutline,
  'starOutline': starOutline,
  'funnel-outline': funnelOutline,
  'funnelOutline': funnelOutline,
  'swap-vertical-outline': swapVerticalOutline,
  'swapVerticalOutline': swapVerticalOutline,
  'close-outline': closeOutline,
  'closeOutline': closeOutline,
  'home-outline': homeOutline,
  'homeOutline': homeOutline,
  'flame': flame,
  'flame-outline': flameOutline,
  'flameOutline': flameOutline,
  'sparkles-outline': sparklesOutline,
  'sparklesOutline': sparklesOutline,
  'refresh-outline': refreshOutline,
  'refreshOutline': refreshOutline,
  'save-outline': saveOutline,
  'saveOutline': saveOutline,
  'information-circle-outline': informationCircleOutline,
  'informationCircleOutline': informationCircleOutline,
  'checkmark-outline': checkmarkOutline,
  'checkmarkOutline': checkmarkOutline,
  'arrow-forward-outline': arrowForwardOutline,
  'arrowForwardOutline': arrowForwardOutline,
  'power-outline': powerOutline,
  'powerOutline': powerOutline
});

bootstrapApplication(AppComponent, {
  providers: [
    { provide: RouteReuseStrategy, useClass: IonicRouteStrategy },
    provideIonicAngular(),
    provideRouter(routes, withPreloading(PreloadAllModules)),
  ],
});
